// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiauvyulzwhfhfsfzuug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpYXV2eXVsendoZmhmc2Z6dXVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTQ0NDIsImV4cCI6MjA3MzU5MDQ0Mn0.Ze2fliyur4khgwas3rnSZYTHQuYfG7aMs4zyeIohyUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});